name: "pull_request"

on:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: Setup Consul
        run: docker run --rm -d -p 8500:8500 --name consul consul:latest
      - name: Run Tests
        run: go test
      - name: Clean Up
        run: docker stop consul